# Generated by Django 3.2 on 2026-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('usex', models.CharField(max_length=100)),
                ('uage', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
